// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlgoliaSearchBox: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/AlgoliaSearchBox.vue')['default']
    ArrowLeft: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/icons/ArrowLeft.vue')['default']
    ArrowRight: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/icons/ArrowRight.vue')['default']
    BuySellAds: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/BuySellAds.vue')['default']
    CarbonAds: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/CarbonAds.vue')['default']
    DarkSwitch: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/DarkSwitch.vue')['default']
    EditLink: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/EditLink.vue')['default']
    GithubLink: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/GithubLink.vue')['default']
    Home: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/Home.vue')['default']
    HomeFeatures: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/HomeFeatures.vue')['default']
    HomeFooter: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/HomeFooter.vue')['default']
    HomeHero: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/HomeHero.vue')['default']
    LangSwitch: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/LangSwitch.vue')['default']
    LastUpdated: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/LastUpdated.vue')['default']
    NavBar: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/NavBar.vue')['default']
    NavBarTitle: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/NavBarTitle.vue')['default']
    NavDropdownLink: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/NavDropdownLink.vue')['default']
    NavDropdownLinkItem: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/NavDropdownLinkItem.vue')['default']
    NavLink: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/NavLink.vue')['default']
    NavLinks: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/NavLinks.vue')['default']
    NextAndPrevLinks: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/NextAndPrevLinks.vue')['default']
    OutboundLink: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/icons/OutboundLink.vue')['default']
    Page: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/Page.vue')['default']
    PageFooter: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/PageFooter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/SideBar.vue')['default']
    SideBarLinks: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/SideBarLinks.vue')['default']
    Slugs: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/Slugs.vue')['default']
    Toast: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/Toast.vue')['default']
    ToggleSideBarButton: typeof import('./../node_modules/.pnpm/fisand-doc@0.0.20_esbuild@0.16.14+rollup@2.79.1/node_modules/fisand-doc/dist/client/theme-default/components/ToggleSideBarButton.vue')['default']
  }
}

export {}
